version: '3.8'

services:
  auth-service:
    build:
      context: ./AttendanceTrackingSystemAuthService
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - student-attendance
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8081/api/health" ]
      interval: 10s
      retries: 3
      timeout: 5s
      start_period: 20s

  attendance-service:
    build:
      context: ./AttendanceTrackingSystemAttendanceService
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      - student-attendance
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8082/api/health" ]
      interval: 10s
      retries: 3
      timeout: 5s
      start_period: 20s
      
#  cassandra:
#    build: .
#    image: cassandra
#    container_name: cassandradb
#    volumes:
#      - ./cassandra.yaml:/etc/cassandra/cassandra.yaml
#    ports:
#      - "9042:9042"
#    networks:
#      - student-attendance

networks:
  student-attendance:
    driver: bridge
